export const CREATE_USER = 'CREATE';
export const UPDATE_USER = 'UPDATE';
export const DELETE_USER = 'DELETE';
export const FETCH_ALL = "FETCH_ALL";
export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SET_USER='SET_USER';
export const CREATE_POST="CREATE_POST";
export const GET_POST="GET_POST";
export const CREATE_COMMENT="CREATE_COMMENT";
export const GET_COMMENT="GET_COMMENT";
export const GET_POST_ID="GET_POST_ID"
export const LOGIN_USER_POST="LOGIN_USER_POST"
export const LOGIN_USER_COMMENT="LOGIN_USER_COMMENT"
export const SET_USER_POST='SET_USER_POST'
export const AUTO_SEARCH="AUTO_SEARCH"
export const CREATE_TASK="CREATE_TASK"
export const GET_TASK="GET_TASK"
export const FILTER_USER_TASK="FILTER_USER_TASK"

